spring.application.name=reservas

# Configuración de base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# update: actualiza el esquema si hay cambios; create: lo borra y crea siempre
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# (Opcional) Si quieres seguir usando H2 y acceder a su consola (para pruebas),
# puedes mantener estas propiedades comentadas o dejarlas si corres perfiles distintos.
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
